### ISSUE TITLE
No function of angle2dcm or dcm2angle

### ISSUE THREAD

**Issue by jianghaizhu** [ronisbr/Rotations.jl#1]
Hi,

I am trying to using your Rotations.jl. The julia version is 0.4.5. 

After "using Rotations", I tried to use the function angle2dcm or dcm2angle, julia couldn't find the functions. Instead I got errors as follows. 

Couldn't find angle2dcm
Perhaps you meant angle
ERROR: "angle2dcm" is not defined in module Main
 in error at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in which_module at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in call at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib

Jianghai

**Comment by ronisbr** [comment]
Hi @jianghaizhu,

It is working for me. Can you please describe how did you install this package?

**Comment by jianghaizhu** [comment]
I just did Pkg.add("Rotations"). I checked it by Pkg.status() and it showed that Rotations has version 0.1.0.

**Comment by ronisbr** [comment]
This package is not a official Julia package. The command you used will not install it. You will have to clone the tree using git inside the right directory of Julia.

In Linux, it is done by:

```
cd ~/.julia/v0.4/
git clone https://github.com/ronisbr/Rotations.jl
```

**Comment by jianghaizhu** [comment]
Thanks. It is working now.
